### PR TITLE
[Stardog] Update to version 7

### PR DESCRIPTION
**Pull request by ZuGao**
#### What this PR does / why we need it:
Update stardog to ver.7.2.0

#### Checklist

- [x] [DCO](https://github.com/appuio/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR contains starts with chart name e.g. `[chart]`

### CODE REVIEW

**Comment by srueg** [comment]
Since Stardog 7 provides [Prometheus metrics natively](https://www.stardog.com/docs/#_accessing_monitoring_information) we don't need the JMX exporter sidecar anymore. Can you please adapt the PR and remove the sidecar and all configuration that goes with it?

**Comment by srueg** [comment]
> Since Stardog 7 provides Prometheus metrics natively we don't need the JMX exporter sidecar anymore. Can you please adapt the PR and remove the sidecar and all configuration that goes with it?

On further investigation it seems the new Prometheus metrics don't include everything we had with the JMX exporter. For now we'll leave the exporter in place, also for v7.

**Comment by ZuGao** [comment]
So after careful consideration we decided that this merge request will be merged tomorrow due to migration that is taking place. The sidecar jmx exporter will be disabled as it does not work with Stardog 7. Moreover the java monitoring alerts have been removed temporarily as they are not exported in Stardog 7, we opened a ticket for that in Stardog support to make them available in the future through their Prometheus endpoint but for now those alerts have been removed.

**Comment by ZuGao** [comment]
Rebased the branch on master to resolve merge conflicts

**Pull request merged**
